---
- name: 'Ensure packages'
  ansible.builtin.package:
    name:
      - 'podman'
    state: 'present'

- name: 'Ensure registry configuration'
  ansible.builtin.template:
    src: 'registries.conf.j2'
    dest: '/etc/containers/registries.conf'
    mode: 0644
    owner: 'root'
    group: 'root'

- name: 'Ensure storage confuguration'
  community.general.ini_file:
    path: '/etc/containers/storage.conf'
    section: "{{ storage['section'] }}"
    option: "{{ storage['option'] }}"
    value: "{{ storage['value'] }}"
    mode: 0644
    owner: 'root'
    group: 'root'
  loop: "{{ podman_storage }}"
  when: podman_storage | length > 0

- name: 'Ensure services'
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: 'started'
    enabled: true
    daemon_reload: true
  loop:
    - 'podman'
  loop_control:
    loop_var: 'service'
