---
- name: 'Ensure packages'
  ansible.builtin.package:
    name:
      - 'podman'
    state: 'present'

- name: 'Ensure registry configuration'
  ansible.builtin.template:
    src: 'registries.conf.j2'
    dest: '/etc/containers/registries.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Ensure storage configuration'
  community.general.ini_file:
    path: '/etc/containers/storage.conf'
    section: "{{ storage['section'] }}"
    option: "{{ storage['option'] }}"
    value: "\"{{ storage['value'] }}\""
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ podman_storage }}"
  loop_control:
    loop_var: 'storage'
  when: podman_storage | length > 0

- name: 'Ensure containers configuration'
  community.general.ini_file:
    path: '/etc/containers/containers.conf'
    section: "{{ containers['section'] }}"
    option: "{{ containers['option'] }}"
    value: "\"{{ storage['value'] }}\""
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: 'containers'
  when: podman_containers | length > 0

- name: 'Ensure Podman services'
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'started'
    enabled: true
  loop:
    - 'podman.socket'
    - 'podman-auto-update.timer'
  loop_control:
    loop_var: 'service'

- name: 'Remove user sockets for Podman'
  ansible.builtin.file:
    path: "{{ file }}"
    state: 'absent'
  loop:
    - '/usr/lib/systemd/user/podman-auto-update.service'
    - '/usr/lib/systemd/user/podman-auto-update.timer'
    - '/usr/lib/systemd/user/podman-kube@.service'
    - '/usr/lib/systemd/user/podman-restart.service'
    - '/usr/lib/systemd/user/podman.service'
    - '/usr/lib/systemd/user/podman.socket'
  loop_control:
    loop_var: 'file'
  when: 'podman_disable_user_sockets'
