---
- name: 'Converge'
  hosts: 'all'
  tasks:
    - name: 'Run role'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    podman_containers:
      - section: 'engine'
        option: 'service_timeout'
        value: 1
    podman_storage:
      - section: 'storage'
        option: 'driver'
        value: 'overlay'
